# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnbot < Formula
  desc "Lightning wallets for agents — CLI"
  homepage "https://ln.bot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lnbotdev/cli/releases/download/v0.2.0/lnbot_darwin_amd64.tar.gz"
      sha256 "0f9bf41a7c8f65037da55ba10d916897b81afd81be36d45470f92cb585ed6f3c"

      define_method(:install) do
        bin.install "lnbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lnbotdev/cli/releases/download/v0.2.0/lnbot_darwin_arm64.tar.gz"
      sha256 "adb25f3b01947c97d97296ece877b55eb505a33b66362634bd8fd2f3918bd667"

      define_method(:install) do
        bin.install "lnbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lnbotdev/cli/releases/download/v0.2.0/lnbot_linux_amd64.tar.gz"
      sha256 "7ac490ef062997ef47c16559b5dcd8de835695e9c6c50eea90e40958ef50b957"
      define_method(:install) do
        bin.install "lnbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lnbotdev/cli/releases/download/v0.2.0/lnbot_linux_arm64.tar.gz"
      sha256 "68c6b2d4f08960a9e10052e9997f0f46a60088395ed93eb65cedb8c4de85015c"
      define_method(:install) do
        bin.install "lnbot"
      end
    end
  end

  test do
    assert_match "lnbot", shell_output("#{bin}/lnbot version")
  end
end
