# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnbot < Formula
  desc "Lightning wallets for agents — CLI"
  homepage "https://ln.bot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lnbotdev/cli/releases/download/v0.1.0/lnbot_darwin_amd64.tar.gz"
      sha256 "cdd4a40b31e628982eb0d7270d979fc213433b2c5d65b2d175c5c79fe977f399"

      define_method(:install) do
        bin.install "lnbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lnbotdev/cli/releases/download/v0.1.0/lnbot_darwin_arm64.tar.gz"
      sha256 "f584a43536a38ee37c02b8326a27c022d5c632d711e66d15ef071d929fe41e2a"

      define_method(:install) do
        bin.install "lnbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lnbotdev/cli/releases/download/v0.1.0/lnbot_linux_amd64.tar.gz"
      sha256 "08a2224f106d95696050be5db9bbc748278821ee9480fbfdc33674fbb584f7ed"
      define_method(:install) do
        bin.install "lnbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lnbotdev/cli/releases/download/v0.1.0/lnbot_linux_arm64.tar.gz"
      sha256 "87c63f276e88496d9c625c7d530085f8f5becfb1695ce352aa29bdb16f7c204c"
      define_method(:install) do
        bin.install "lnbot"
      end
    end
  end

  test do
    assert_match "lnbot", shell_output("#{bin}/lnbot version")
  end
end
